import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./shared/SideBar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Muhammad Noman",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="container mx-auto lg:flex">
          <div>
            <SideBar />
          </div>
          <div className="ml-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
